--version: add unix time

diff --git a/a b/a
--- a/a
+++ b/a
@@ -22,20 +22,18 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
-#git <hbc/e35ca7a>
-#nix <1658843067>
-#hbc <e35ca7a>
-#lib <stdlib/ask.sh/1eaba1f>
-#lib <stdlib/debug.sh/1eaba1f>
-#lib <stdlib/log.sh/1eaba1f>
-#lib <stdlib/readonly.sh/1eaba1f>
-#lib <stdlib/trace.sh/1eaba1f>
+#git <hbc/7f27eed>
+#nix <1659731963>
+#hbc <7f27eed>
+#lib <stdlib/ask.sh/8038e38>
+#lib <stdlib/debug.sh/8038e38>
+#lib <stdlib/log.sh/8038e38>
+#lib <stdlib/readonly.sh/8038e38>
+#lib <stdlib/trace.sh/8038e38>
 
 #-------------------------------------------------------------------------------- BEGIN SAFETY
 POSIXLY_CORRECT= || exit 90
-	# bash builtins
 \unset -f alias bg bind break builtin caller cd command compgen complete compopt continue declare dirs disown echo enable eval exec exit export false fc fg getopts hash help history jobs kill let local logout mapfile popd printf pushd pwd read readarray readonly return set shift shopt source suspend test times trap true type typeset ulimit umask unalias unset wait || exit 91
-	# gnu core-utils
 \unset -f arch base64 basename cat chcon chgrp chmod chown chroot cksum comm cp csplit cut date dd df dir dircolors dirname du echo env expand expr factor false fmt fold groups head hostid hostname id install join kill link ln logname ls md5sum mkdir mkfifo mknod mktemp mv nice nl nohup nproc numfmt od paste pathchk pinky pr printenv printf ptx pwd readlink realpath rm rmdir runcon seq shred shuf sleep sort split stat stdbuf stty sum tac tail tee test timeout touch tr true truncate tsort tty uname unexpand uniq unlink uptime users vdir wc who whoami yes || exit 92
 \unalias -a || exit 93
 unset POSIXLY_CORRECT || exit 94
@@ -110,34 +108,13 @@ debug::trap() {
 	done
 	printf "\033[0m\n"
 }
-log::ok() {
-	printf "\r\e[2K"
-	printf "\r\e[1;32m[  OK  ]\e[0m %s\n" "$@"
-}
-log::info() {
-	printf "\r\e[2K"
-	printf "\r\e[1;37m[ INFO ]\e[0m %s\n" "$@"
-}
-log::warn() {
-	printf "\r\e[2K"
-	printf "\r\e[1;33m[ WARN ]\e[0m %s\n" "$@"
-}
-log::fail() {
-	printf "\r\e[2K"
-	printf "\r\e[1;31m[ FAIL ]\e[0m %s\n" "$@"
-}
-log::danger() {
-	printf "\r\e[2K"
-	printf "\r\e[1;31m[DANGER]\e[0m %s\n" "$@"
-}
-log::tab() {
-	printf "\r\e[2K"
-	printf "\r\e[0m         %s\n" "$@"
-}
-log::prog() {
-	printf "\r\e[2K"
-	printf "\r\e[1;37m[ \e[0m....\e[1;37m ]\e[0m %s " "$@"
-}
+log::ok() { printf "\r\e[2K\e[1;32m[  OK  ]\e[0m %s\n" "$@"; }
+log::info() { printf "\r\e[2K\e[1;37m[ INFO ]\e[0m %s\n" "$@"; }
+log::warn() { printf "\r\e[2K\e[1;33m[ WARN ]\e[0m %s\n" "$@"; }
+log::fail() { printf "\r\e[2K\e[1;31m[ FAIL ]\e[0m %s\n" "$@"; }
+log::danger() { printf "\r\e[2K\e[1;31m[DANGER]\e[0m %s\n" "$@"; }
+log::tab() { printf "\r\e[2K\e[0m         %s\n" "$@"; }
+log::prog() { printf "\r\e[2K\e[1;37m[ \e[0m....\e[1;37m ]\e[0m %s " "$@"; }
 log::debug() {
 	[[ $STD_LOG_DEBUG != true ]] && return 0
 	if [[ $STD_LOG_DEBUG_LAST_FUNC != "${FUNCNAME[1]}" ]]; then
@@ -250,10 +227,6 @@ ___ENDOF___ERROR___TRACE___() {
 	unset -v POSIXLY_CORRECT || exit 18
 	unset -f : || exit 1
 	if [[ -z $STD_TRACE_PIPE ]]; then
-		POSIXLY_CORRECT= || exit 19
-		\unset -f trap set return exit return || exit 20
-		\unalias -a || exit 21
-		unset POSIXLY_CORRECT || exit 22
 		unset -v STD_TRACE_CMD STD_TRACE_FUNC_NUM STD_TRACE_CMD_NUM STD_TRACE_PIPE || exit 23
 		set +E +eo pipefail || exit 24
 		trap - ERR || exit 25
@@ -353,8 +326,8 @@ printf "${BPURPLE}%s${OFF}%s${BPURPLE}%s${BYELLOW}%s${OFF}%s\n" \
 "    -a" " |" " --add" "     <text file>" "          add a text file (like a license) on top of output, default: [LICENSE]" \
 "    -c" " |" " --config" "  <hbc config file>" "    specify hbc config to use, default: [\$PWD/hbc.conf] or [/etc/hbc.conf]"
 printf "${BPURPLE}%s${OFF}%s${BPURPLE}%s${OFF}%s\n" \
-"    -d" " |" " --delete" "                       overwrite output file if it already exists"
-"    -f" " |" " --full" "                      "  "fully clean the output, including [main.sh]"
+"    -d" " |" " --delete" "                       overwrite output file if it already exists" \
+"    -f" " |" " --full" "                         fully clean the output, including [main.sh]"
 printf "${BPURPLE}%s${OFF}%s${BPURPLE}%s${BYELLOW}%s${OFF}%s\n" \
 "    -i" " |" " --ignore" "  <codes> or <ALL>" "     ignore shellcheck codes or disable shellcheck: [-i SC2154,SC2155] or [-i ALL]" \
 "    -l" " |" " --library" " <library directory>" "  specify where to look for lib code, default: [/usr/local/include]" \
@@ -378,7 +351,7 @@ printf "${OFF}%s\n" \
 	"Copyright (c) 2022 hinto-janaiyo <https://github.com/hinto-janaiyo>"
 exit 2
 elif [[ $* = *"-v"* || $* = *"--version"* ]]; then
-	printf "%s\n" "2022 July 26 - e35ca7aadd540b201dbd2e20c38af29b12bfcd9d"
+	printf "%s\n" "2022 August 05 | 1659731963 | 7f27eed51a6fd6e2a97be4cdf186bfbc58336667"
 	exit 3
 fi
 unset -v ADD OPTIONS CONFIG FULL LICENSE DELETE IGNORE LIBRARY MAIN OUTPUT QUIET RUN SOURCE TEST
@@ -826,7 +799,7 @@ if [[ $EXISTS_MAIN ]]; then
 	echo "$ENDOF_MAIN" >> "$OUTPUT"
 	if [[ $DIRECTORY_NAME = hbc ]]; then
 		local VERSION_LINE
-		VERSION_LINE="$(printf "%s\n" "$(date -d @$EPOCHSECONDS "+%Y %B %d") - $(git rev-parse HEAD 2>/dev/null)")"
+		VERSION_LINE="$(printf "%s\n" "$(date -d @$EPOCHSECONDS "+%Y %B %d") | $EPOCHSECONDS | $(git rev-parse HEAD 2>/dev/null)")"
 		VERSION_LINE='printf "%s\\n" '\""$VERSION_LINE"\"''
 		sed -i '0,/___TEMPORARY___LINE___MEANT___FOR___REPLACEMENT___/s//'"$VERSION_LINE"'/' $OUTPUT
 		log::tab "hbc version replacement"
@@ -838,20 +811,22 @@ chmod 700 "${OUTPUT}"
 if [[ $IGNORE = *ALL* || $IGNORE = *all* ]]; then
 	log::warn "skipping shellcheck"
 else
+	___ENDOF___ERROR___TRACE___
 	log::info "starting shellcheck"
 	if [[ $QUIET = true ]]; then
 		if [[ $IGNORE ]]; then
-			shellcheck "${OUTPUT}" --shell bash -e "$IGNORE" >&3
+			shellcheck "${OUTPUT}" --shell bash -e "$IGNORE" >&3 || exit
 		else
-			shellcheck "${OUTPUT}" --shell bash >&3
+			shellcheck "${OUTPUT}" --shell bash >&3 || exit
 		fi
 	else
 		if [[ $IGNORE ]]; then
-			shellcheck "${OUTPUT}" --shell bash -e "$IGNORE"
+			shellcheck "${OUTPUT}" --shell bash -e "$IGNORE" || exit
 		else
-			shellcheck "${OUTPUT}" --shell bash
+			shellcheck "${OUTPUT}" --shell bash || exit
 		fi
 	fi
+	___BEGIN___ERROR___TRACE___
 fi
 if [[ $TEST != true ]]; then
 	log::info "deleting $TMP_DIR"
