sed: fix sed deleting non-comments like: "#
sed "/^#\|[[:space:]]#/d" > sed "/^#\|^[[:space:]]#/d"
this was deleting quotes that start with # because it
didn't check if the line was empty before it.

diff --git a/a b/a
--- a/a
+++ b/a
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
-#git <hbc/f87076b>
-#nix <1656989385>
-#hbc <f78c459>
-#lib <stdlib/ask.sh/6cf3ad6>
-#lib <stdlib/log.sh/6cf3ad6>
-#lib <stdlib/trace.sh/6cf3ad6>
-#lib <stdlib/var.sh/6cf3ad6>
+#git <hbc/20cccca>
+#nix <1657044047>
+#hbc <ed139bd>
+#lib <stdlib/ask.sh/cc3d85c>
+#lib <stdlib/log.sh/cc3d85c>
+#lib <stdlib/trace.sh/cc3d85c>
+#lib <stdlib/var.sh/cc3d85c>
 
 #-------------------------------------------------------------------------------- BEGIN LIB CODE
 POSIXLY_CORRECT=;\unset -f trap set unset declare exit printf read unalias;\unalias -a
@@ -159,7 +159,8 @@ ___ENDOF___ERROR___TRACE___() {
 	unset -v TRACE_CMD TRACE_FUNC_NUM TRACE_CMD_NUM TRACE_PIPE || exit 26
 	set +E +eo pipefail || exit 27
 	trap - ERR || exit 28
-	builtin kill -s SIGKILL $$ & exit 99
+	builtin kill -s SIGKILL $$
+	exit 99
 	printf "\033[1;97m%s\033[0m\n" "= KILL FAIL, ENTERING INFINITE LOOP ="
 	while :; do read -s -r; done
 }
@@ -344,7 +345,7 @@ local ENDOF_MAIN="#-------------------------------------------------------------
 
 # GIT HASH
 local DIRECTORY_GIT
-DIRECTORY_GIT=$(git rev-parse --short HEAD 2>/dev/null) || true
+DIRECTORY_GIT=$(git rev-parse --short HEAD 2>/dev/null) || unset DIRECTORY_GIT
 
 # HBC VERSION
 local VERSION_HBC
@@ -438,12 +439,18 @@ echo "#hbc <$VERSION_HBC>" >> "$TMP_HEADER"
 if [[ $EXISTS_LIB = true && $DIRECTORY_NAME != *lib ]]; then
 	printf "${BPURPLE}%s${OFF}\n" "compiling [lib] ******************"
 	local i
+	# include each found #include in TMP_LIB
 	for i in $(grep "^#include <.*>$" "$main" | cut -d ' ' -f2 | tr -d '<>' | sort); do
 		if [[ $i = *.sh && -f "$LIB_DIRECTORY/$i" ]]; then
 			sed "/^#\|[[:space:]]#/d" "$LIB_DIRECTORY/$i" >> "$TMP_LIB"
-			LIB_GIT=$(grep "^#git <.*>$" "$LIB_DIRECTORY/$i" | cut -d ' ' -f2)
-			log::tab "$LIB_GIT"
-			echo "#lib $LIB_GIT" >> "$TMP_HEADER"
+			# if #git is found in the lib file, attach to TMP_HEADER
+			if LIB_GIT=$(grep "^#git <.*>$" "$LIB_DIRECTORY/$i" | cut -d ' ' -f2); then
+				log::tab "$LIB_GIT"
+				echo "#lib $LIB_GIT" >> "$TMP_HEADER"
+			else
+				log::warn "<lib missing #git>"
+				echo "#lib <UNKNOWN>" >> "$TMP_HEADER"
+			fi
 		else
 			log::fail "$i not *.sh || $i not found"
 			exit 1
