stdlib: new trace/panic

diff --git a/a b/a
--- a/a
+++ b/a
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
-#git <hbc/6dfe9a3>
-#nix <1656816410>
+#git <hbc/7edbd54>
+#nix <1656858786>
 #hbc <6dfe9a3>
 #lib <stdlib/ask.sh/6cf3ad6>
 #lib <stdlib/log.sh/6cf3ad6>
@@ -8,8 +8,10 @@
 #lib <stdlib/var.sh/6cf3ad6>
 
 #-------------------------------------------------------------------------------- BEGIN LIB CODE
+POSIXLY_CORRECT=;\unset -f trap set unset declare exit printf read unalias;\unalias -a
 set -eo pipefail || exit 111
-trap 'printf "%s\n" "@@@@@@ LIB PANIC @@@@@@" "[line] ${LINENO}" "[file] $0" "[code] $?";set +eo pipefail;trap - ERR;while :;do read;done;exit 112' ERR || exit 113
+trap 'printf "%s\n" "@@@@@@ LIB PANIC @@@@@@" "[line] ${LINENO}" "[file] $0" "[code] $?";set +eo pipefail;trap - ERR;while :;do read;done;exit 112' ERR || exit 112
+unset POSIXLY_CORRECT || exit 113
 ask::yes() {
 	local ASK_FUNC_RESPONSE || return 44
 	read -r ASK_FUNC_RESPONSE
@@ -169,7 +171,7 @@ if [[ $1 = "-h" || $1 = "--help" ]]; then
 cat << EOM
 HBC USAGE
     -d | --delete                       overwrite output file if it already exists
-	-i | --ignore  <shellcheck codes>   ignore shellcheck codes, formatting: SC2154,SC2155
+    -i | --ignore  <shellcheck codes>   ignore shellcheck codes, formatting: SC2154,SC2155
     -m | --main    <main script name>   specify main script name, default: [main.sh]
     -h | --help                         print this help message and exit unsuccessfully
     -o | --output  <output name>        specify output filename, default: [${FOLDER_NAME}.sh]
