hbc: integrate const

diff --git a/a b/a
--- a/a
+++ b/a
@@ -1,15 +1,15 @@
 #!/usr/bin/env bash
-#git <hbc/877affa>
-#nix <1656532717>
-#hbc <91d2b52>
-#lib <stdlib/ask.sh/e3af68e>
-#lib <stdlib/log.sh/e3af68e>
-#lib <stdlib/trace.sh/e3af68e>
-#lib <stdlib/var.sh/e3af68e>
+#git <hbc/1b4405c>
+#nix <1656601813>
+#hbc <1b4405c>
+#lib <stdlib/ask.sh/0e67503>
+#lib <stdlib/log.sh/0e67503>
+#lib <stdlib/trace.sh/0e67503>
+#lib <stdlib/var.sh/0e67503>
 
 #-------------------------------------------------------------------------------- BEGIN LIB CODE
 set -eo pipefail || exit 111
-trap 'printf "%s\n" "@@@@@@ LIB PANIC @@@@@@" "[ \$_ ] ${LINENO}: $BASH_COMMAND" "[file] $0" "[code] $?";while :;do read;done;exit 112' ERR || exit 113
+trap 'printf "%s\n" "@@@@@@ LIB PANIC @@@@@@" "[line] ${LINENO}" "[file] $0" "[code] $?";set +eo pipefail;trap - ERR;while :;do read;done;exit 112' ERR || exit 113
 ask::yes(){
 	local ASK_FUNC_RESPONSE || return 44
 	read -r ASK_FUNC_RESPONSE
@@ -39,65 +39,82 @@ log::warn(){ printf "\033[1;33m[ WARN ]\033[0m %s\n" "$@" ;}
 log::fail(){ printf "\033[1;31m[ FAIL ]\033[0m %s\n" "$@" ;}
 log::danger(){ printf "\033[1;31m[DANGER]\033[0m %s\n" "$@" ;}
 ___BEGIN___ERROR___TRACE___(){
-	trap 'TRACE_CMD="$BASH_COMMAND" TRACE_FUNC="$BASH_LINENO" TRACE_CMD_NUM="$LINENO" TRACE_CODE="$?" TRACE_PIPE="${PIPESTATUS[@]}"; ___ENDOF___ERROR___TRACE___ || exit 100' ERR || exit 11
+	trap 'TRACE_CMD="$BASH_COMMAND" TRACE_FUNC="${BASH_LINENO[@]}" TRACE_CMD_NUM="$LINENO" TRACE_CODE="$?" TRACE_PIPE="${PIPESTATUS[@]}"; ___ENDOF___ERROR___TRACE___ || exit 100' ERR || exit 11
 	unset TRACE_CMD TRACE_FUNC_NUM TRACE_CMD_NUM TRACE_CODE TRACE_PIPE || exit 22
-	set -e -o pipefail || exit 33
+	set -E -e -o pipefail || exit 33
 	return 0
 }
 ___ENDOF___ERROR___TRACE___(){
 	if [[ -z $TRACE_CODE ]]; then
-		set +e +o pipefail || exit 44
+		set +E +eo pipefail || exit 44
 		trap - ERR || exit 55
 		return 0
 	fi
 	printf "\033[1;91m%s\n" "========  BEGIN ERROR TRACE  ========"
-	printf "\033[1;34m%s\033[0m%s\n" "[  \$_  ] " "${TRACE_CMD_NUM}: $TRACE_CMD"
-	printf "\033[1;32m%s\033[0m%s\n" "[ func ] " "${TRACE_FUNC}: ${FUNCNAME[1]}()"
-	printf "\033[1;37m%s\033[0m%s\n" "[ file ] " "${BASH_SOURCE[-1]}"
-	printf "\033[1;31m%s\033[0m%s\n" "[ code ] " "$TRACE_CODE"
-	printf "\033[1;35m%s\033[0m%s\n" "[ pipe ] " "${TRACE_PIPE[@]}"
-	printf "\033[1;92m%s\033[0m%s\n" "[ bash ] " "$BASH_VERSION"
-	printf "\033[1;96m%s\033[0m%s\n" "[ unix ] " "$EPOCHSECONDS"
-	printf "\033[1;93m%s\033[0m%s\n" "[  wd  ] " "$PWD"
+	printf "\033[1;92m%s\033[0m%s\n" "[bash] " "$BASH_VERSION"
+	printf "\033[1;96m%s\033[0m%s\n" "[unix] " "$EPOCHSECONDS"
+	printf "\033[1;91m%s\033[0m%s\n" "[code] " "$TRACE_CODE"
+	printf "\033[1;95m%s\033[0m%s\n" "[pipe] " "${TRACE_PIPE[@]}"
+	printf "\033[1;97m%s\033[0m%s\n" "[file] " "${BASH_SOURCE[-1]}"
+	printf "\033[1;93m%s\033[0m%s\n" "[ wd ] " "$PWD"
+	printf "\033[1;94m%s\033[0m%s\n" "[ \$_ ] " "${TRACE_CMD_NUM}: $TRACE_CMD"
+	local f
+	local i=1
+	for f in ${TRACE_FUNC[@]}; do
+		[[ $f = 0 ]] && break
+		printf "\033[1;92m%s\033[0m%s\n" "[func] " "${f}: ${FUNCNAME[${i}]}()"
+		((i++))
+	done
+	if [[ $TRACE_CMD_NUM -lt 5 ]]; then
+		printf "\033[1;90m%s\n\033[1;97m%s\n\033[1;90m%s\033[0;m\n" \
+			"$(sed -n "1,$((TRACE_CMD_NUM-1)) p" $0 | nl -s' ' -ba -v 1)" \
+			"$(sed -n "$TRACE_CMD_NUM p" $0 | nl -s' ' -ba -v $TRACE_CMD_NUM)" \
+			"$(sed -n "$((TRACE_CMD_NUM+1)),$((TRACE_CMD_NUM+4)) p" $0 | nl -s' ' -ba -v $((TRACE_CMD_NUM+1)))"
+	else
+		printf "\033[1;90m%s\n\033[1;97m%s\n\033[1;90m%s\033[0;m\n" \
+			"$(sed -n "$((TRACE_CMD_NUM-4)),$((TRACE_CMD_NUM-1)) p" $0 | nl -s' ' -ba -v $((TRACE_CMD_NUM-4)))" \
+			"$(sed -n "$TRACE_CMD_NUM p" $0 | nl -s' ' -ba -v $TRACE_CMD_NUM)" \
+			"$(sed -n "$((TRACE_CMD_NUM+1)),$((TRACE_CMD_NUM+4)) p" $0 | nl -s' ' -ba -v $((TRACE_CMD_NUM+1)))"
+	fi
 	printf "\033[1;91m%s\n" "========  ENDOF ERROR TRACE  ========"
 	unset TRACE_CMD TRACE_FUNC_NUM TRACE_CMD_NUM TRACE_CODE TRACE_PIPE || exit 66
-	set +e +o pipefail || exit 77
-	trap - EXIT || exit 88
+	set +E +eo pipefail || exit 77
+	trap - ERR || exit 88
 	exit 99
 }
-BLACK="\033[0;30m"
-RED="\033[0;31m"
-GREEN="\033[0;32m"
-YELLOW="\033[0;33m"
-BLUE="\033[0;34m"
-PURPLE="\033[0;35m"
-CYAN="\033[0;36m"
-WHITE="\033[0;37m"
-BBLACK="\033[1;30m"
-BRED="\033[1;31m"
-BGREEN="\033[1;32m"
-BYELLOW="\033[1;33m"
-BBLUE="\033[1;34m"
-BPURPLE="\033[1;35m"
-BCYAN="\033[1;36m"
-BWHITE="\033[1;37m"
-UBLACK="\033[4;30m"
-URED="\033[4;31m"
-UGREEN="\033[4;32m"
-UYELLOW="\033[4;33m"
-UBLUE="\033[4;34m"
-UPURPLE="\033[4;35m"
-UCYAN="\033[4;36m"
-UWHITE="\033[4;37m"
-IBLACK="\033[0;90m"
-IRED="\033[0;91m"
-IGREEN="\033[0;92m"
-IYELLOW="\033[0;93m"
-IBLUE="\033[0;94m"
-IPURPLE="\033[0;95m"
-ICYAN="\033[0;96m"
-IWHITE="\033[0;97m"
-OFF="\033[0m"
+readonly BLACK="\033[0;30m"
+readonly RED="\033[0;31m"
+readonly GREEN="\033[0;32m"
+readonly YELLOW="\033[0;33m"
+readonly BLUE="\033[0;34m"
+readonly PURPLE="\033[0;35m"
+readonly CYAN="\033[0;36m"
+readonly WHITE="\033[0;37m"
+readonly BBLACK="\033[1;90m"
+readonly BRED="\033[1;91m"
+readonly BGREEN="\033[1;92m"
+readonly BYELLOW="\033[1;93m"
+readonly BBLUE="\033[1;94m"
+readonly BPURPLE="\033[1;95m"
+readonly BCYAN="\033[1;96m"
+readonly BWHITE="\033[1;97m"
+readonly UBLACK="\033[4;30m"
+readonly URED="\033[4;31m"
+readonly UGREEN="\033[4;32m"
+readonly UYELLOW="\033[4;33m"
+readonly UBLUE="\033[4;34m"
+readonly UPURPLE="\033[4;35m"
+readonly UCYAN="\033[4;36m"
+readonly UWHITE="\033[4;37m"
+readonly IBLACK="\033[0;90m"
+readonly IRED="\033[0;91m"
+readonly IGREEN="\033[0;92m"
+readonly IYELLOW="\033[0;93m"
+readonly IBLUE="\033[0;94m"
+readonly IPURPLE="\033[0;95m"
+readonly ICYAN="\033[0;96m"
+readonly IWHITE="\033[0;97m"
+readonly OFF="\033[0m"
 trap - ERR || exit 117
 set +eo pipefail || exit 118
 
@@ -201,13 +218,13 @@ TMP_SCRATCH="$(mktemp "$TMP_DIR"/scratch.XXXXXXXXXX)"
 local SAFETY_LIB
 SAFETY_LIB=$(cat << 'EOM'
 set -eo pipefail || exit 111
-trap 'printf "%s\n" "@@@@@@ LIB PANIC @@@@@@" "[ \$_ ] ${LINENO}: $BASH_COMMAND" "[file] $0" "[code] $?";set +eo pipefail; trap - ERR; while :;do read;done;exit 112' ERR || exit 113
+trap 'printf "%s\n" "@@@@@@ LIB PANIC @@@@@@" "[line] ${LINENO}" "[file] $0" "[code] $?";set +eo pipefail;trap - ERR;while :;do read;done;exit 112' ERR || exit 113
 EOM
 )
 local SAFETY_SRC
 SAFETY_SRC=$(cat << 'EOM'
 set -eo pipefail || exit 114
-trap 'printf "%s\n" "@@@@@@ SRC PANIC @@@@@@" "[ \$_ ] ${LINENO}: $BASH_COMMAND" "[file] $0" "[code] $?";;set +eo pipefail; trap - ERR; while :;do read;done;exit 115' ERR || exit 116
+trap 'printf "%s\n" "@@@@@@ SRC PANIC @@@@@@" "[line] ${LINENO}" "[file] $0" "[code] $?";set +eo pipefail;trap - ERR;while :;do read;done;exit 115' ERR || exit 116
 EOM
 )
 local SAFETY_END
@@ -321,35 +338,63 @@ printf "${BGREEN}%s${OFF}\n" "linking  *************************"
 
 # HEADER
 cat "$TMP_HEADER" > "$out"
-log::tab "[header] ------> line $(wc -l "$out" | cut -f1 -d ' ')"
+log::tab "[header] -------> line $(wc -l "$out" | cut -f1 -d ' ')"
 
 # LIB
 if [[ $EXISTS_LIB = true && $DIRECTORY_NAME != *lib ]]; then
-	log::tab "[lib::header] -> line $(wc -l "$out" | cut -f1 -d ' ')"
+	log::tab "[lib::header] --> line $(wc -l "$out" | cut -f1 -d ' ')"
 	echo >> "$out"
 	echo "$HEADER_LIB" >> "$out"
-	log::tab "[lib::safety] -> line $(wc -l "$out" | cut -f1 -d ' ')"
+	log::tab "[lib::safety] --> line $(wc -l "$out" | cut -f1 -d ' ')"
 	echo "$SAFETY_LIB" >> "$out"
-	log::tab "[lib] ---------> line $(wc -l "$out" | cut -f1 -d ' ')"
+	log::tab "[lib] ----------> line $(wc -l "$out" | cut -f1 -d ' ')"
 	cat "$TMP_LIB" >> "$out"
+	# DECLARE -FR
+	log::tab "[lib::declare] -> line $(wc -l "$out" | cut -f1 -d ' ')"
+	local FUNCTIONS_LIB
+	if FUNCTIONS_LIB=($(grep -ho "^[0-9A-Za-z:_-]\+(){\|^[0-9A-Za-z:_-]\+()[[:blank:]]\+{" "$TMP_LIB" | tr -d '(){ ')); then
+		if [[ -z ${FUNCTIONS_LIB[0]} ]]; then
+			log::fail "no functions found"
+			exit 3
+		fi
+		local d
+		for d in ${FUNCTIONS_LIB[@]}; do
+			echo "declare -fr $d" >> "$out"
+		done
+	fi
 fi
 
 # SRC
 if [[ $SRC_FILES ]]; then
-	log::tab "[src::header] -> line $(wc -l "$out" | cut -f1 -d ' ')"
+	log::tab "[src::header] --> line $(wc -l "$out" | cut -f1 -d ' ')"
 	echo >> "$out"
 	echo "$HEADER_SRC" >> "$out"
 	if [[ $DIRECTORY_NAME != *lib ]]; then
-		log::tab "[src::safety] -> line $(wc -l "$out" | cut -f1 -d ' ')"
+		log::tab "[src::safety] --> line $(wc -l "$out" | cut -f1 -d ' ')"
 		echo "$SAFETY_SRC" >> "$out"
 	fi
-	log::tab "[src] ---------> line $(wc -l "$out" | cut -f1 -d ' ')"
+	log::tab "[src] ----------> line $(wc -l "$out" | cut -f1 -d ' ')"
 	cat "$TMP_SRC" >> "$out"
+	# DECLARE -FR
+	if [[ $DIRECTORY_NAME != *lib ]]; then
+		log::tab "[src::declare] -> line $(wc -l "$out" | cut -f1 -d ' ')"
+		local FUNCTIONS_SRC
+		if FUNCTIONS_SRC=($(grep -ho "^[0-9A-Za-z:_-]\+(){\|^[0-9A-Za-z:_-]\+()[[:blank:]]\+{" "$TMP_SRC" | tr -d '(){ ')); then
+			if [[ -z ${FUNCTIONS_SRC[0]} ]]; then
+				log::fail "no functions found"
+				exit 3
+			fi
+			local d
+			for d in ${FUNCTIONS_SRC[@]}; do
+				echo "declare -fr $d" >> "$out"
+			done
+		fi
+	fi
 fi
 
 # SAFETY END
 if [[ $DIRECTORY_NAME != *lib ]]; then
-	log::tab "[safety::end] -> line $(wc -l "$out" | cut -f1 -d ' ')"
+	log::tab "[safety::end] --> line $(wc -l "$out" | cut -f1 -d ' ')"
 	echo "$SAFETY_END" >> "$out"
 fi
 
