safety header: disable set and trap if trap set

diff --git a/a b/a
--- a/a
+++ b/a
@@ -1,8 +1,107 @@
-#include <stdlib/ask.sh>
-#include <stdlib/log.sh>
-#include <stdlib/trace.sh>
-#include <stdlib/var.sh>
+#!/usr/bin/env bash
+#git <hbc/877affa>
+#nix <1656532717>
+#hbc <91d2b52>
+#lib <stdlib/ask.sh/e3af68e>
+#lib <stdlib/log.sh/e3af68e>
+#lib <stdlib/trace.sh/e3af68e>
+#lib <stdlib/var.sh/e3af68e>
 
+#-------------------------------------------------------------------------------- BEGIN LIB CODE
+set -eo pipefail || exit 111
+trap 'printf "%s\n" "@@@@@@ LIB PANIC @@@@@@" "[ \$_ ] ${LINENO}: $BASH_COMMAND" "[file] $0" "[code] $?";while :;do read;done;exit 112' ERR || exit 113
+ask::yes(){
+	local ASK_FUNC_RESPONSE || return 44
+	read -r ASK_FUNC_RESPONSE
+	case $ASK_FUNC_RESPONSE in
+		""|y|Y|yes|Yes|YES) return 0 ;;
+		*) return 2 ;;
+	esac
+}
+ask::no(){
+	local ASK_FUNC_RESPONSE || return 44
+	read -r ASK_FUNC_RESPONSE
+	case $ASK_FUNC_RESPONSE in
+		y|Y|yes|Yes|YES) return 2 ;;
+		*) return 0 ;;
+	esac
+}
+ask::sudo(){
+	sudo -v
+	return
+}
+log::dot(){ printf "\033[1;37m[ \033[0m....\033[1;37m ]\033[0m %s\r" "$@" ;}
+log::prog(){ printf "\033[1;37m[ \033[0m....\033[1;37m ]\033[0m %s\n" "$@" ;}
+log::tab(){ printf "\033[0m         %s\n" "$@" ;}
+log::ok(){ printf "\033[1;32m[  OK  ]\033[0m %s\n" "$@" ;}
+log::info(){ printf "\033[1;37m[ INFO ]\033[0m %s\n" "$@" ;}
+log::warn(){ printf "\033[1;33m[ WARN ]\033[0m %s\n" "$@" ;}
+log::fail(){ printf "\033[1;31m[ FAIL ]\033[0m %s\n" "$@" ;}
+log::danger(){ printf "\033[1;31m[DANGER]\033[0m %s\n" "$@" ;}
+___BEGIN___ERROR___TRACE___(){
+	trap 'TRACE_CMD="$BASH_COMMAND" TRACE_FUNC="$BASH_LINENO" TRACE_CMD_NUM="$LINENO" TRACE_CODE="$?" TRACE_PIPE="${PIPESTATUS[@]}"; ___ENDOF___ERROR___TRACE___ || exit 100' ERR || exit 11
+	unset TRACE_CMD TRACE_FUNC_NUM TRACE_CMD_NUM TRACE_CODE TRACE_PIPE || exit 22
+	set -e -o pipefail || exit 33
+	return 0
+}
+___ENDOF___ERROR___TRACE___(){
+	if [[ -z $TRACE_CODE ]]; then
+		set +e +o pipefail || exit 44
+		trap - ERR || exit 55
+		return 0
+	fi
+	printf "\033[1;91m%s\n" "========  BEGIN ERROR TRACE  ========"
+	printf "\033[1;34m%s\033[0m%s\n" "[  \$_  ] " "${TRACE_CMD_NUM}: $TRACE_CMD"
+	printf "\033[1;32m%s\033[0m%s\n" "[ func ] " "${TRACE_FUNC}: ${FUNCNAME[1]}()"
+	printf "\033[1;37m%s\033[0m%s\n" "[ file ] " "${BASH_SOURCE[-1]}"
+	printf "\033[1;31m%s\033[0m%s\n" "[ code ] " "$TRACE_CODE"
+	printf "\033[1;35m%s\033[0m%s\n" "[ pipe ] " "${TRACE_PIPE[@]}"
+	printf "\033[1;92m%s\033[0m%s\n" "[ bash ] " "$BASH_VERSION"
+	printf "\033[1;96m%s\033[0m%s\n" "[ unix ] " "$EPOCHSECONDS"
+	printf "\033[1;93m%s\033[0m%s\n" "[  wd  ] " "$PWD"
+	printf "\033[1;91m%s\n" "========  ENDOF ERROR TRACE  ========"
+	unset TRACE_CMD TRACE_FUNC_NUM TRACE_CMD_NUM TRACE_CODE TRACE_PIPE || exit 66
+	set +e +o pipefail || exit 77
+	trap - EXIT || exit 88
+	exit 99
+}
+BLACK="\033[0;30m"
+RED="\033[0;31m"
+GREEN="\033[0;32m"
+YELLOW="\033[0;33m"
+BLUE="\033[0;34m"
+PURPLE="\033[0;35m"
+CYAN="\033[0;36m"
+WHITE="\033[0;37m"
+BBLACK="\033[1;30m"
+BRED="\033[1;31m"
+BGREEN="\033[1;32m"
+BYELLOW="\033[1;33m"
+BBLUE="\033[1;34m"
+BPURPLE="\033[1;35m"
+BCYAN="\033[1;36m"
+BWHITE="\033[1;37m"
+UBLACK="\033[4;30m"
+URED="\033[4;31m"
+UGREEN="\033[4;32m"
+UYELLOW="\033[4;33m"
+UBLUE="\033[4;34m"
+UPURPLE="\033[4;35m"
+UCYAN="\033[4;36m"
+UWHITE="\033[4;37m"
+IBLACK="\033[0;90m"
+IRED="\033[0;91m"
+IGREEN="\033[0;92m"
+IYELLOW="\033[0;93m"
+IBLUE="\033[0;94m"
+IPURPLE="\033[0;95m"
+ICYAN="\033[0;96m"
+IWHITE="\033[0;97m"
+OFF="\033[0m"
+trap - ERR || exit 117
+set +eo pipefail || exit 118
+
+#-------------------------------------------------------------------------------- BEGIN MAIN SCRIPT
 hbc() {
 #-------------------------------------------------------------------------------- SANITY CHECKS
 # NO SRC DIR
@@ -102,13 +201,13 @@ TMP_SCRATCH="$(mktemp "$TMP_DIR"/scratch.XXXXXXXXXX)"
 local SAFETY_LIB
 SAFETY_LIB=$(cat << 'EOM'
 set -eo pipefail || exit 111
-trap 'printf "%s\n" "@@@@@@ LIB PANIC @@@@@@" "[line] ${LINENO}" "[file] $0" "[code] $?";set +eo pipefail;trap - ERR;while :;do read;done;exit 112' ERR || exit 113
+trap 'printf "%s\n" "@@@@@@ LIB PANIC @@@@@@" "[ \$_ ] ${LINENO}: $BASH_COMMAND" "[file] $0" "[code] $?";set +eo pipefail; trap - ERR; while :;do read;done;exit 112' ERR || exit 113
 EOM
 )
 local SAFETY_SRC
 SAFETY_SRC=$(cat << 'EOM'
 set -eo pipefail || exit 114
-trap 'printf "%s\n" "@@@@@@ SRC PANIC @@@@@@" "[line] ${LINENO}" "[file] $0" "[code] $?";set +eo pipefail;trap - ERR;while :;do read;done;exit 115' ERR || exit 116
+trap 'printf "%s\n" "@@@@@@ SRC PANIC @@@@@@" "[ \$_ ] ${LINENO}: $BASH_COMMAND" "[file] $0" "[code] $?";;set +eo pipefail; trap - ERR; while :;do read;done;exit 115' ERR || exit 116
 EOM
 )
 local SAFETY_END
@@ -286,3 +385,4 @@ log::ok "hbc done"
 ___ENDOF___ERROR___TRACE___
 }
 hbc $@
+#-------------------------------------------------------------------------------- ENDOF MAIN SCRIPT
