stdlib/trace: fix multi-subshell output

diff --git a/hbc b/hbc
--- a/hbc
+++ b/hbc
@@ -22,9 +22,9 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
-#git <hbc/fdd861a>
-#nix <1657200995>
-#hbc <fdd861a>
+#git <hbc/c3b8806>
+#nix <1657219177>
+#hbc <c3b8806>
 #lib <stdlib/ask.sh/9c906b1>
 #lib <stdlib/log.sh/9c906b1>
 #lib <stdlib/trace.sh/9c906b1>
@@ -146,19 +146,19 @@ log::debug() {
 }
 ___BEGIN___ERROR___TRACE___() {
 	POSIXLY_CORRECT= || exit 8
-	\unset -f trap set return exit printf unset local return read unalias mapfile kill builtin || exit 9
+	\unset -f : true false trap set return exit printf unset local return read unalias mapfile kill builtin wait || exit 9
 	\unalias -a || exit 10
-	unset POSIXLY_CORRECT || exit 11
-	trap 'STD_TRACE_CMD="$BASH_COMMAND" STD_TRACE_FUNC=(${BASH_LINENO[@]}) STD_TRACE_CMD_NUM="$LINENO" STD_TRACE_PIPE=(${PIPESTATUS[@]}); ___ENDOF___ERROR___TRACE___ || exit 100' ERR || exit 12
+	unset -v POSIXLY_CORRECT || exit 11
+	trap 'STD_TRACE_CMD="$BASH_COMMAND" STD_TRACE_FUNC=(${BASH_LINENO[@]}) STD_TRACE_CMD_NUM="$LINENO" STD_TRACE_PIPE=(${PIPESTATUS[@]}); ___ENDOF___ERROR___TRACE___ > /dev/tty || exit 100' ERR || exit 12
 	unset -v STD_TRACE_CMD STD_TRACE_FUNC_NUM STD_TRACE_CMD_NUM STD_TRACE_PIPE || exit 13
 	set -E -e -o pipefail || exit 14
 	return 0
 }
 ___ENDOF___ERROR___TRACE___() {
 	POSIXLY_CORRECT= || exit 15
-	\unset -f trap set return exit printf unset local return read unalias mapfile kill builtin || exit 16
+	\unset -f : true false trap set return exit printf unset local return read unalias mapfile kill builtin wait || exit 16
 	\unalias -a || exit 17
-	unset POSIXLY_CORRECT || exit 18
+	unset -v POSIXLY_CORRECT || exit 18
 	if [[ -z $STD_TRACE_PIPE ]]; then
 		POSIXLY_CORRECT= || exit 19
 		\unset -f trap set return exit return || exit 20
@@ -219,14 +219,19 @@ ___ENDOF___ERROR___TRACE___() {
 		((STD_TRACE_CMD_NUM++))
 	done
 	printf "\033[1;91m%s\033[0m\n" "========  ENDOF ERROR TRACE  ========"
-	[[ $STD_TRACE_CMD =~ ^\(.*\)$ ]] && printf "\033[1;93m%s\033[0m\n" "========  SUB-SHELLS KILLED  ========"
 	unset -v STD_TRACE_CMD STD_TRACE_FUNC_NUM STD_TRACE_CMD_NUM STD_TRACE_PIPE || exit 26
 	set +E +eo pipefail || exit 27
 	trap - ERR || exit 28
-	builtin kill -s SIGKILL $$
+	if [[ $BASH_SUBSHELL != 0 ]]; then
+		printf "\033[1;93m%s\033[0m\n" "========  SUB-SHELLS KILLED  ========"
+		builtin kill -s KILL 0
+	fi
 	exit 99
-	printf "\033[1;97m%s\033[0m\n" "= KILL FAIL, ENTERING INFINITE LOOP ="
+	printf "\033[1;97m%s\033[0m\n" "=KILL/EXIT FAIL, BEGIN INFINITE LOOP="
 	while :; do read -s -r; done
+	while true; do read -s -r; done
+	while true; do false; done
+	while :; do :; done
 }
 readonly BLACK="\033[0;30m"
 readonly RED="\033[0;31m"
@@ -313,7 +318,7 @@ printf "${OFF}%s\n" \
 exit 2
 # VERSION OPTION
 elif [[ $* = *"-v"* || $* = *"--version"* ]]; then
-	printf "%s\n" "2022 July 07 - fdd861a42f936f8091d918adc04518b34800078b"
+	printf "%s\n" "2022 July 07 - c3b880650ae8ca184423488519598cc74acb262f"
 	exit 3
 fi
 
