safety: include builtin sanity checks in headers

diff --git a/hbc b/hbc
--- a/hbc
+++ b/hbc
@@ -1,15 +1,17 @@
 #!/usr/bin/env bash
-#git <hbc/0f3609d>
-#nix <1656650438>
-#hbc <0f3609d>
-#lib <stdlib/ask.sh/76f0927>
-#lib <stdlib/log.sh/76f0927>
-#lib <stdlib/trace.sh/76f0927>
-#lib <stdlib/var.sh/76f0927>
+#git <hbc/6dfe9a3>
+#nix <1656816413>
+#hbc <6dfe9a3>
+#lib <stdlib/ask.sh/6cf3ad6>
+#lib <stdlib/log.sh/6cf3ad6>
+#lib <stdlib/trace.sh/6cf3ad6>
+#lib <stdlib/var.sh/6cf3ad6>
 
 #-------------------------------------------------------------------------------- BEGIN LIB CODE
+POSIXLY_CORRECT=;\unset -f trap set unset declare exit printf read unalias;\unalias -a
 set -eo pipefail || exit 111
-trap 'printf "%s\n" "@@@@@@ LIB PANIC @@@@@@" "[line] ${LINENO}" "[file] $0" "[code] $?";set +eo pipefail;trap - ERR;while :;do read;done;exit 112' ERR || exit 113
+trap 'printf "%s\n" "@@@@@@ LIB PANIC @@@@@@" "[line] ${LINENO}" "[file] $0" "[code] $?";set +eo pipefail;trap - ERR;while :;do read;done;exit 112' ERR || exit 112
+unset POSIXLY_CORRECT || exit 113
 ask::yes() {
 	local ASK_FUNC_RESPONSE || return 44
 	read -r ASK_FUNC_RESPONSE
@@ -38,22 +40,30 @@ log::warn() { printf "\033[1;33m[ WARN ]\033[0m %s\n" "$@" ;}
 log::fail() { printf "\033[1;31m[ FAIL ]\033[0m %s\n" "$@" ;}
 log::danger() { printf "\033[1;31m[DANGER]\033[0m %s\n" "$@" ;}
 ___BEGIN___ERROR___TRACE___() {
-	trap 'TRACE_CMD="$BASH_COMMAND" TRACE_FUNC="${BASH_LINENO[@]}" TRACE_CMD_NUM="$LINENO" TRACE_CODE="$?" TRACE_PIPE="${PIPESTATUS[@]}"; ___ENDOF___ERROR___TRACE___ || exit 100' ERR || exit 11
-	unset TRACE_CMD TRACE_FUNC_NUM TRACE_CMD_NUM TRACE_CODE TRACE_PIPE || exit 22
-	set -E -e -o pipefail || exit 33
+	POSIXLY_CORRECT= || exit 8
+	\unset -f trap set return exit printf echo unset local return read unalias mapfile || exit 9
+	\unalias -a || exit 10
+	unset POSIXLY_CORRECT || exit 11
+	trap 'TRACE_CMD="$BASH_COMMAND" TRACE_FUNC="${BASH_LINENO[@]}" TRACE_CMD_NUM="$LINENO" TRACE_PIPE="${PIPESTATUS[@]}"; ___ENDOF___ERROR___TRACE___ || exit 100' ERR || exit 12
+	unset -v TRACE_CMD TRACE_FUNC_NUM TRACE_CMD_NUM TRACE_PIPE || exit 13
+	set -E -e -o pipefail || exit 14
 	return 0
 }
 ___ENDOF___ERROR___TRACE___() {
-	if [[ -z $TRACE_CODE ]]; then
-		set +E +eo pipefail || exit 44
-		trap - ERR || exit 55
+	if [[ -z $TRACE_PIPE ]]; then
+		POSIXLY_CORRECT= || exit 15
+		\unset -f trap set return exit return || exit 16
+		\unalias -a || exit 17
+		unset POSIXLY_CORRECT || exit 18
+		unset -v TRACE_CMD TRACE_FUNC_NUM TRACE_CMD_NUM TRACE_PIPE || exit 19
+		set +E +eo pipefail || exit 20
+		trap - ERR || exit 21
 		return 0
 	fi
 	printf "\033[1;91m%s\n" "========  BEGIN ERROR TRACE  ========"
-	printf "\033[1;92m%s\033[0m%s\n" "[bash] " "$BASH_VERSION"
+	printf "\033[1;95m%s\033[0m%s\n" "[bash] " "$BASH_VERSION"
 	printf "\033[1;96m%s\033[0m%s\n" "[unix] " "$EPOCHSECONDS"
-	printf "\033[1;91m%s\033[0m%s\n" "[code] " "$TRACE_CODE"
-	printf "\033[1;95m%s\033[0m%s\n" "[pipe] " "${TRACE_PIPE[@]}"
+	printf "\033[1;91m%s\033[0m%s\n" "[code] " "${TRACE_PIPE[@]}"
 	printf "\033[1;97m%s\033[0m%s\n" "[file] " "${BASH_SOURCE[-1]}"
 	printf "\033[1;93m%s\033[0m%s\n" "[ wd ] " "$PWD"
 	printf "\033[1;94m%s\033[0m%s\n" "[ \$_ ] " "${TRACE_CMD_NUM}: $TRACE_CMD"
@@ -64,21 +74,42 @@ ___ENDOF___ERROR___TRACE___() {
 		printf "\033[1;92m%s\033[0m%s\n" "[func] " "${f}: ${FUNCNAME[${i}]}()"
 		((i++))
 	done
+	local TRACE_LINE_ARRAY
+	local ORIGINAL_LINE="$TRACE_CMD_NUM"
 	if [[ $TRACE_CMD_NUM -lt 5 ]]; then
-		printf "\033[1;90m%s\n\033[1;97m%s\n\033[1;90m%s\033[0;m\n" \
-			"$(sed -n "1,$((TRACE_CMD_NUM-1)) p" $0 | nl -s' ' -ba -v 1)" \
-			"$(sed -n "$TRACE_CMD_NUM p" $0 | nl -s' ' -ba -v $TRACE_CMD_NUM)" \
-			"$(sed -n "$((TRACE_CMD_NUM+1)),$((TRACE_CMD_NUM+4)) p" $0 | nl -s' ' -ba -v $((TRACE_CMD_NUM+1)))"
+		local TRACE_CMD_NUM=1
+		mapfile -n 9 TRACE_LINE_ARRAY < $0
 	else
-		printf "\033[1;90m%s\n\033[1;97m%s\n\033[1;90m%s\033[0;m\n" \
-			"$(sed -n "$((TRACE_CMD_NUM-4)),$((TRACE_CMD_NUM-1)) p" $0 | nl -s' ' -ba -v $((TRACE_CMD_NUM-4)))" \
-			"$(sed -n "$TRACE_CMD_NUM p" $0 | nl -s' ' -ba -v $TRACE_CMD_NUM)" \
-			"$(sed -n "$((TRACE_CMD_NUM+1)),$((TRACE_CMD_NUM+4)) p" $0 | nl -s' ' -ba -v $((TRACE_CMD_NUM+1)))"
+		local TRACE_CMD_NUM=$((TRACE_CMD_NUM-4))
+		mapfile -s $((TRACE_CMD_NUM-1)) -n 9 TRACE_LINE_ARRAY < $0
 	fi
-	printf "\033[1;91m%s\n" "========  ENDOF ERROR TRACE  ========"
-	unset TRACE_CMD TRACE_FUNC_NUM TRACE_CMD_NUM TRACE_CODE TRACE_PIPE || exit 66
-	set +E +eo pipefail || exit 77
-	trap - ERR || exit 88
+	for i in {0..8}; do
+		[[ ${TRACE_LINE_ARRAY[$i]} ]] || break
+		if [[ $TRACE_CMD_NUM = "$ORIGINAL_LINE" ]]; then
+			case ${#TRACE_CMD_NUM} in
+				1) printf "\033[1;97m%s" "     $TRACE_CMD_NUM ${TRACE_LINE_ARRAY[${i}]}" ;;
+				2) printf "\033[1;97m%s" "    $TRACE_CMD_NUM ${TRACE_LINE_ARRAY[${i}]}" ;;
+				3) printf "\033[1;97m%s" "   $TRACE_CMD_NUM ${TRACE_LINE_ARRAY[${i}]}" ;;
+				4) printf "\033[1;97m%s" "  $TRACE_CMD_NUM ${TRACE_LINE_ARRAY[${i}]}" ;;
+				5) printf "\033[1;97m%s" " $TRACE_CMD_NUM ${TRACE_LINE_ARRAY[${i}]}" ;;
+				*) printf "\033[1;97m%s" "$TRACE_CMD_NUM ${TRACE_LINE_ARRAY[${i}]}" ;;
+			esac
+		else
+			case ${#TRACE_CMD_NUM} in
+				1) printf "\033[1;90m%s" "     $TRACE_CMD_NUM ${TRACE_LINE_ARRAY[${i}]}" ;;
+				2) printf "\033[1;90m%s" "    $TRACE_CMD_NUM ${TRACE_LINE_ARRAY[${i}]}" ;;
+				3) printf "\033[1;90m%s" "   $TRACE_CMD_NUM ${TRACE_LINE_ARRAY[${i}]}" ;;
+				4) printf "\033[1;90m%s" "  $TRACE_CMD_NUM ${TRACE_LINE_ARRAY[${i}]}" ;;
+				5) printf "\033[1;90m%s" " $TRACE_CMD_NUM ${TRACE_LINE_ARRAY[${i}]}" ;;
+				*) printf "\033[1;90m%s" "$TRACE_CMD_NUM ${TRACE_LINE_ARRAY[${i}]}" ;;
+			esac
+		fi
+		((TRACE_CMD_NUM++))
+	done
+	printf "\033[1;91m%s\033[0m\n" "========  ENDOF ERROR TRACE  ========"
+	unset -v TRACE_CMD TRACE_FUNC_NUM TRACE_CMD_NUM TRACE_PIPE || exit 22
+	set +E +eo pipefail || exit 23
+	trap - ERR || exit 24
 	exit 99
 }
 readonly BLACK="\033[0;30m"
@@ -140,11 +171,12 @@ if [[ $1 = "-h" || $1 = "--help" ]]; then
 cat << EOM
 HBC USAGE
     -d | --delete                       overwrite output file if it already exists
+	-i | --ignore  <shellcheck codes>   ignore shellcheck codes, formatting: SC2154,SC2155
     -m | --main    <main script name>   specify main script name, default: [main.sh]
     -h | --help                         print this help message and exit unsuccessfully
     -o | --output  <output name>        specify output filename, default: [${FOLDER_NAME}.sh]
-    -r | --run                          run output file if hbc successfully compiles
     -q | --quiet                        suppress hbc compile-time output (exit codes stay)
+    -r | --run                          run output file if hbc successfully compiles
     -v | --version                      print this hbc's time of compile and exit unsuccessfully
 EOM
 exit 2
@@ -154,6 +186,7 @@ elif [[ $1 = "-v" || $1 = "--version" ]]; then
 fi
 case $1 in
 	-d | --delete) local OPTION_DELETE=true; shift;;
+	-i | --ignore) shift; local OPTION_IGNORE="$1"; shift;;
 	-m | --main)
 		shift
 		if [[ -z $1 ]]; then
@@ -239,9 +272,7 @@ local ENDOF_MAIN="#-------------------------------------------------------------
 
 # GIT HASH
 local DIRECTORY_GIT
-if DIRECTORY_GIT=$(git rev-parse --short HEAD 2>/dev/null); then
-	:
-fi
+DIRECTORY_GIT=$(git rev-parse --short HEAD 2>/dev/null) || true
 
 # HBC VERSION
 local VERSION_HBC
@@ -276,14 +307,18 @@ TMP_SCRATCH="$(mktemp "$TMP_DIR"/scratch.XXXXXXXXXX)"
 # SAFETY HEADERS
 local SAFETY_LIB
 SAFETY_LIB=$(cat << 'EOM'
+POSIXLY_CORRECT=;\unset -f trap set unset declare exit printf read unalias;\unalias -a
 set -eo pipefail || exit 111
-trap 'printf "%s\n" "@@@@@@ LIB PANIC @@@@@@" "[line] ${LINENO}" "[file] $0" "[code] $?";set +eo pipefail;trap - ERR;while :;do read;done;exit 112' ERR || exit 113
+trap 'printf "%s\n" "@@@@@@ LIB PANIC @@@@@@" "[line] ${LINENO}" "[file] $0" "[code] $?";set +eo pipefail;trap - ERR;while :;do read;done;exit 112' ERR || exit 112
+unset POSIXLY_CORRECT || exit 113
 EOM
 )
 local SAFETY_SRC
 SAFETY_SRC=$(cat << 'EOM'
+POSIXLY_CORRECT=;\unset -f trap set unset declare exit printf read unalias;\unalias -a
 set -eo pipefail || exit 114
-trap 'printf "%s\n" "@@@@@@ SRC PANIC @@@@@@" "[line] ${LINENO}" "[file] $0" "[code] $?";set +eo pipefail;trap - ERR;while :;do read;done;exit 115' ERR || exit 116
+trap 'printf "%s\n" "@@@@@@ SRC PANIC @@@@@@" "[line] ${LINENO}" "[file] $0" "[code] $?";set +eo pipefail;trap - ERR;while :;do read;done;exit 115' ERR || exit 115
+unset POSIXLY_CORRECT || exit 116
 EOM
 )
 local SAFETY_END
@@ -481,7 +516,7 @@ chmod 700 "${OUTPUT}"
 
 # SHELLCHECK
 log::info "starting shellcheck"
-shellcheck "${OUTPUT}" --shell bash -e SC2274,SC2068,SC2128,SC2086,SC1036,SC1088,SC2153,SC2034,SC2155,SC2207,SC2119,SC2120,SC2044,SC2035,SC2129
+shellcheck "${OUTPUT}" --shell bash -e SC2274,SC2068,SC2128,SC2086,SC1036,SC1088,SC2153,SC2034,SC2155,SC2207,SC2119,SC2120,SC2044,SC2035,SC2129,${OPTION_IGNORE}
 
 # DELETE TMP_DIR
 log::info "deleting $TMP_DIR"
