option: add [--bang] to specify shebang, add safe env as default

diff --git a/hbc b/hbc
--- a/hbc
+++ b/hbc
@@ -1,4 +1,4 @@
-#!/usr/bin/bash
+#!/usr/bin/env -iS EDITOR="${EDITOR}" HOME="${HOME}" LANG="${LANG}" PATH="${PATH}" PWD="${PWD}" TERM="${TERM}" USER="${USER}" STD_LOG_DEBUG="${STD_LOG_DEBUG}" STD_DEBUG="${STD_DEBUG}" bash
 #
 # hbc - hinto's bash compiler
 #
@@ -22,9 +22,9 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
-#git <hbc/a93fdb9>
-#nix <1662169687>
-#hbc <a93fdb9>
+#git <hbc/68c9d60>
+#nix <1663282455>
+#hbc <68c9d60>
 #lib <stdlib/ask.sh/4c8490f>
 #lib <stdlib/debug.sh/4c8490f>
 #lib <stdlib/log.sh/4c8490f>
@@ -41,7 +41,7 @@ unset -f . : [ || exit 94
 set -eo pipefail || exit 95
 
 #-------------------------------------------------------------------------------- BEGIN LIB
-trap 'printf "%s\n" "@@@@@@ LIB PANIC @@@@@@" "[line] ${LINENO}: ${BASH_COMMAND}" "[file] $_" "[code] $?";set +eo pipefail;trap - ERR;exit 111;while :;do read;done' ERR || exit 112
+trap 'printf "%s\n" "@@@@@@ LIB PANIC @@@@@@" "[line] ${LINENO}: ${BASH_COMMAND}" "[file] ${BASH_SOURCE}" "[code] $?";exit 111;while :;do read;done' ERR || exit 112
 ask::yes() {
 	local STD_ASK_REPONSE || return 44
 	read -r STD_ASK_REPONSE
@@ -151,18 +151,18 @@ log::debug() {
 	fi
 }
 readonly BLACK="\e[0;30m" RED="\e[0;31m" GREEN="\e[0;32m" YELLOW="\e[0;33m" BLUE="\e[0;34m" PURPLE="\e[0;35m" CYAN="\e[0;36m" WHITE="\e[0;37m" BBLACK="\e[1;90m" BRED="\e[1;91m" BGREEN="\e[1;92m" BYELLOW="\e[1;93m" BBLUE="\e[1;94m" BPURPLE="\e[1;95m" BCYAN="\e[1;96m" BWHITE="\e[1;97m" UBLACK="\e[4;30m" URED="\e[4;31m" UGREEN="\e[4;32m" UYELLOW="\e[4;33m" UBLUE="\e[4;34m" UPURPLE="\e[4;35m" UCYAN="\e[4;36m" UWHITE="\e[4;37m" IBLACK="\e[0;90m" IRED="\e[0;91m" IGREEN="\e[0;92m" IYELLOW="\e[0;93m" IBLUE="\e[0;94m" IPURPLE="\e[0;95m" ICYAN="\e[0;96m" IWHITE="\e[0;97m" BOLD="\e[1m" ITALIC="\e[3m" OFF="\e[m" RESET_LINE="\r\e[2K" NEW_BUFFER="\e[?1049h" OLD_BUFFER="\e[?1049l" HIDE_CURSOR="\e[?25l" SHOW_CURSOR="\e[?25h"
-___BEGIN___ERROR___TRACE___() {
+___BEGIN___TRACE___() {
 	POSIXLY_CORRECT= || exit 8
 	\unset -f true false trap set return exit printf unset local return read unalias mapfile kill builtin wait || exit 9
 	\unalias -a || exit 10
 	unset -v POSIXLY_CORRECT || exit 11
 	unset -f : || exit 1
-	trap 'STD_TRACE_CMD="$BASH_COMMAND" STD_TRACE_FUNC=(${BASH_LINENO[@]}) STD_TRACE_CMD_NUM="$LINENO" STD_TRACE_PIPE=(${PIPESTATUS[@]}); ___ENDOF___ERROR___TRACE___ > /dev/tty || exit 100' ERR || exit 12
+	trap 'STD_TRACE_CMD="$BASH_COMMAND" STD_TRACE_FUNC=(${BASH_LINENO[@]}) STD_TRACE_CMD_NUM="$LINENO" STD_TRACE_PIPE=(${PIPESTATUS[@]}); ___ENDOF___TRACE___ > /dev/tty || exit 100' ERR || exit 12
 	unset -v STD_TRACE_CMD STD_TRACE_FUNC_NUM STD_TRACE_CMD_NUM STD_TRACE_PIPE || exit 13
 	set -E -e -o pipefail || exit 14
 	return 0
 }
-___ENDOF___ERROR___TRACE___() {
+___ENDOF___TRACE___() {
 	POSIXLY_CORRECT= || exit 15
 	\unset -f true false trap set return exit printf unset local return read unalias mapfile kill builtin wait || exit 16
 	\unalias -a || exit 17
@@ -174,14 +174,12 @@ ___ENDOF___ERROR___TRACE___() {
 		trap - ERR || exit 25
 		return 0
 	fi
-	printf "\e[1;91m%s\n" "========  BEGIN ERROR TRACE  ========"
-	printf "\e[1;95m%s\e[0m%s\n" "[bash] " "$BASH_VERSION"
-	printf "\e[1;96m%s\e[0m%s\n" "[unix] " "$EPOCHSECONDS"
-	printf "\e[1;91m%s" "[code] "
+	printf "\e[1;91m%s\n" "========  BEGIN TRACE  ========"
+	printf "\e[1;96m%s" "[code] "
 	for i in "${STD_TRACE_PIPE[@]}"; do
 		printf "\e[0m%s" "$i"
 	done
-	printf "\n\e[1;97m%s\e[0m%s\n" "[file] " "${BASH_SOURCE[-1]}"
+	printf "\n\e[1;95m%s\e[0m%s\n" "[file] " "${BASH_SOURCE[-1]}"
 	printf "\e[1;94m%s\e[0m%s\n" "[ wd ] " "$PWD"
 	printf "\e[1;93m%s\e[0m%s\n" "[ \$_ ] " "${STD_TRACE_CMD_NUM}: $STD_TRACE_CMD"
 	local f
@@ -224,78 +222,89 @@ ___ENDOF___ERROR___TRACE___() {
 		fi
 		((STD_TRACE_CMD_NUM++))
 	done
+	if [[ $STD_LOG_DEBUG = true ]]; then
+		printf "\e[0;91m%s\e[0m\n" "=======  VARIABLE DUMP  ======="
+		declare -p
+	fi
 	[[ $STD_TRACE_RETURN ]] && printf "\e[38;5;196m%s\e[0;1m%s\e[0m\n" "[STD_TRACE_RETURN]" " $STD_TRACE_RETURN"
-	printf "\e[1;91m%s\e[0m\n" "========  ENDOF ERROR TRACE  ========"
+	printf "\e[1;91m%s\e[0m\n" "========  ENDOF TRACE  ========"
 	unset -v STD_TRACE_CMD STD_TRACE_FUNC_NUM STD_TRACE_CMD_NUM STD_TRACE_PIPE || exit 26
 	set +E +eo pipefail || exit 27
 	trap - ERR || exit 28
 	if [[ $BASH_SUBSHELL != 0 ]]; then
-		printf "\e[1;93m%s\e[0m\n" "======  SUB-SHELLS TERMINATED  ======"
+		printf "\e[1;93m%s\e[0m\n" "===  SUB-SHELLS TERMINATED  ==="
 		builtin kill -s TERM 0
 	fi
 	exit 99
-	printf "\e[1;97m%s\e[0m\n" "=KILL/EXIT FAIL, BEGIN INFINITE LOOP="
+	printf "\e[1;97m%s\e[0m\n" "!KILL/EXIT FAIL, INFINITE LOOP!"
 	while :; do read -s -r; done
 	while true; do read -s -r; done
 	while true; do false; done
 	while :; do :; done
 }
-declare -frg ask::yes ask::no ask::sudo debug debug::trap log::ok log::info log::warn log::fail log::danger log::tab log::prog log::debug ___BEGIN___ERROR___TRACE___ ___ENDOF___ERROR___TRACE___
+declare -frg ask::yes ask::no ask::sudo debug debug::trap log::ok log::info log::warn log::fail log::danger log::tab log::prog log::debug ___BEGIN___TRACE___ ___ENDOF___TRACE___
 trap - ERR || exit 115
 set +eo pipefail || exit 116
 
 #-------------------------------------------------------------------------------- BEGIN MAIN
 hbc() {
 #-------------------------------------------------------------------------------- HBC OPTIONS
-___BEGIN___ERROR___TRACE___
+___BEGIN___TRACE___
 debug
 # HELP OPTION
 if [[ $* = *"-h"* || $* = *"--help"* ]]; then
 printf "${BWHITE}%s${OFF}%s${BPURPLE}%s${BYELLOW}%s\n\n" "USAGE: " "hbc " "--OPTION " "<ARGUMENT>"
 printf "${BPURPLE}%s${OFF}%s${BPURPLE}%s${BYELLOW}%s${OFF}%s\n" \
-"    -a" " |" " --add" "     <text file>" "          add a text file (like a license) on top of output, default: [LICENSE]" \
-"    -c" " |" " --config" "  <hbc config file>" "    specify hbc config to use, default: [\$PWD/hbc.conf] or [/etc/hbc.conf]"
+"    -a" " |" " --add" "     <text file>" "          Add a text file (like a license) on top of output, default: [LICENSE]" \
+"    -b" " |" " --bang" "    <shebang type>" "       Specify a shebang to use, default is Bash with a minimal environment" \
+"    -c" " |" " --config" "  <hbc config file>" "    Specify hbc config to use, default: [\$PWD/hbc.conf] or [/etc/hbc.conf]"
 printf "${BPURPLE}%s${OFF}%s${BPURPLE}%s${OFF}%s\n" \
-"    -d" " |" " --delete" "                       overwrite output file if it already exists" \
-"    -e" " |" " --expose" "                       expose all whitespace/comments, don't clean the output" \
-"    -f" " |" " --full" "                         fully clean the output, including [main.sh]"
+"    -d" " |" " --delete" "                       Overwrite output file if it already exists" \
+"    -e" " |" " --expose" "                       Expose all whitespace/comments, don't clean the output" \
+"    -f" " |" " --full" "                         Fully clean the output, including [main.sh]"
 printf "${BPURPLE}%s${OFF}%s${BPURPLE}%s${BYELLOW}%s${OFF}%s\n" \
-"    -i" " |" " --ignore" "  <codes> or <ALL>" "     ignore shellcheck codes or disable shellcheck: [-i SC2154,SC2155] or [-i ALL]" \
-"    -l" " |" " --library" " <library directory>" "  specify where to look for lib code, default: [/usr/local/include]" \
-"    -m" " |" " --main" "    <main script name>" "   specify main script name, default: [main.sh]"
+"    -i" " |" " --ignore" "  <codes> or <ALL>" "     Ignore shellcheck codes or disable shellcheck: [-i SC2154,SC2155] or [-i ALL]" \
+"    -l" " |" " --library" " <library directory>" "  Specify where to look for lib code, default: [/usr/local/include]" \
+"    -m" " |" " --main" "    <main script name>" "   Specify main script name, default: [main.sh]"
 printf "${BPURPLE}%s${OFF}%s${BPURPLE}%s${OFF}%s\n" \
-"    -h" " |" " --help" "                         print this help message and exit unsuccessfully"
+"    -h" " |" " --help" "                         Print this help message and exit unsuccessfully"
 printf "${BPURPLE}%s${OFF}%s${BPURPLE}%s${BYELLOW}%s${OFF}%s\n" \
-"    -o" " |" " --output" "  <output name>" "        specify output filename, default: [\$FOLDER_NAME.sh]"
+"    -o" " |" " --output" "  <output name>" "        Specify output filename, default: [\$FOLDER_NAME.sh]"
 printf "${BPURPLE}%s${OFF}%s${BPURPLE}%s${OFF}%s\n" \
-"    -q" " |" " --quiet" "                        suppress hbc compile-time output (exit codes stay)" \
-"    -r" " |" " --run" "                          run output file if hbc successfully compiles"
+"    -q" " |" " --quiet" "                        Suppress hbc compile-time output (exit codes stay)" \
+"    -r" " |" " --run" "                          Run output file if hbc successfully compiles"
 printf "${BPURPLE}%s${OFF}%s${BPURPLE}%s${BYELLOW}%s${OFF}%s\n" \
-"    -s" " |" " --source" "  <source directory>" "   specify where to look for src code, default: [src]"
+"    -s" " |" " --source" "  <source directory>" "   Specify where to look for src code, default: [src]"
 printf "${BPURPLE}%s${OFF}%s${BPURPLE}%s${OFF}%s\n" \
-"    -t" " |" " --test" "                         --run & --quiet the output from memory, no file made" \
-"    -v" " |" " --version" "                      print this hbc's time of compile and exit unsuccessfully"
+"    -t" " |" " --test" "                         [--run] & [--quiet] the output from memory, no file made" \
+"    -v" " |" " --version" "                      Print this hbc's time of compile and exit unsuccessfully"
 printf "${OFF}%s\n" \
 	"" \
 	"hbc - hinto's bash compiler" \
-	"Full documentation <https://github.com/hinto-janaiyo/hbc>" \
-	"Copyright (c) 2022 hinto-janaiyo <https://github.com/hinto-janaiyo>"
+	"Full documentation: <https://github.com/hinto-janaiyo/hbc>" \
+	"Copyright (c) 2022, hinto-janaiyo <https://github.com/hinto-janaiyo>"
 exit 2
 # VERSION OPTION
 elif [[ $* = *"-v"* || $* = *"--version"* ]]; then
-	printf "%s\n" "2022 September 02 | 1662169687 | a93fdb9ce6e0e37a5d13ce71479ee03c4c8f0d5d"
+	printf "%s\n" "2022 September 15 | 1663282455 | 68c9d602688921ed1600f74db2d8e826f67c80a1"
 	exit 3
 fi
 
 # UNSET ENVIRONMENT
-unset -v ADD OPTIONS CONFIG FULL LICENSE DELETE EXPOSE IGNORE LIBRARY MAIN OUTPUT QUIET RUN SOURCE TEST
+#unset -v ADD OPTIONS CONFIG FULL LICENSE DELETE EXPOSE IGNORE LIBRARY MAIN OUTPUT QUIET RUN SOURCE TEST
 
 # PARSE CONFIG FILE (because directly sourcing is spooky)
 hbc_parse_config() {
 	local i IFS=$'\n' OPTIONS || return 1
 	mapfile OPTIONS < $1 || return 2
 	for i in ${OPTIONS[@]}; do
-	    [[ $i =~ ^ADD=[[:alnum:]./_-]*$ ]]                   && declare -g LICENSE="${i/*=/}"
+		[[ $i =~ ^ADD=[[:alnum:]./_-]*$ ]]                   && declare -g LICENSE="${i/*=/}"
+		# shebang is complicated, needs to be parsed
+		if [[ $i =~ ^BANG=.*'#!'.*$ ]]; then
+			BANG="${i/BANG=\'}"
+			BANG="${BANG/BANG=\"}"
+			declare -g BANG="${BANG:0:-1}"
+		fi
 	    [[ $i =~ ^DELETE=true[[:space:]]*$ ]]                && declare -g DELETE=true
 	    [[ $i =~ ^EXPOSE=true[[:space:]]*$ ]]                && declare -g EXPOSE=true
 		[[ $i =~ ^FULL=true[[:space:]]*$ ]]                  && declare -g FULL=true
@@ -313,6 +322,7 @@ hbc_parse_config() {
 	log::debug \
 		"=== hbc_parse_config ===" \
 		"ADD     | $LICENSE" \
+		"BANG    | $BANG"    \
 		"CONFIG  | $CONFIG"  \
 		"DELETE  | $DELETE"  \
 		"EXPOSE  | $EXPOSE"  \
@@ -372,6 +382,13 @@ case $1 in
 			exit 1
 		fi
 		LICENSE="$1"; shift;;
+	-b | --bang)
+		shift
+		if [[ -z $1 ]]; then
+			log::fail "hbc: no arg after --bang"
+			exit 1
+		fi
+		BANG="$1"; shift;;
 	-c | --config) shift; shift;;
 	-d | --delete) local DELETE=true; shift;;
 	-e | --expose) local EXPOSE=true; shift;;
@@ -419,7 +436,7 @@ esac
 done
 # to make the config test work
 [[ $TEST = true ]] && RUN=true QUIET=true
-___ENDOF___ERROR___TRACE___
+___ENDOF___TRACE___
 
 #-------------------------------------------------------------------------------- SANITY CHECKS
 # CONFIG
@@ -488,10 +505,14 @@ elif [[ $OUTPUT != [A-Za-z0-9_/]* ]]; then
 fi
 
 # DEBUG OPTION PRINTS
-log::debug "=== post --option debug ===" \
+log::debug \
+	"=== hbc_parse_config ===" \
 	"ADD     | $LICENSE" \
+	"BANG    | $BANG"    \
 	"CONFIG  | $CONFIG"  \
 	"DELETE  | $DELETE"  \
+	"EXPOSE  | $EXPOSE"  \
+	"FULL    | $FULL"    \
 	"IGNORE  | $IGNORE"  \
 	"LIBRARY | $LIBRARY" \
 	"MAIN    | $MAIN"    \
@@ -515,7 +536,7 @@ fi
 [[ $QUIET = true ]] && exec 3>&1 &>/dev/null
 
 #-------------------------------------------------------------------------------- VARIABLE INIT
-___BEGIN___ERROR___TRACE___
+___BEGIN___TRACE___
 
 # HEADERS
 local HEADER_SAFETY="#-------------------------------------------------------------------------------- BEGIN SAFETY"
@@ -584,13 +605,13 @@ EOM
 )
 # lib
 SAFETY_LIB=$(cat << 'EOM'
-trap 'printf "%s\n" "@@@@@@ LIB PANIC @@@@@@" "[line] ${LINENO}: ${BASH_COMMAND}" "[file] $_" "[code] $?";set +eo pipefail;trap - ERR;exit 111;while :;do read;done' ERR || exit 112
+trap 'printf "%s\n" "@@@@@@ LIB PANIC @@@@@@" "[line] ${LINENO}: ${BASH_COMMAND}" "[file] ${BASH_SOURCE}" "[code] $?";exit 111;while :;do read;done' ERR || exit 112
 EOM
 )
 # src
 local SAFETY_SRC
 SAFETY_SRC=$(cat << 'EOM'
-trap 'printf "%s\n" "@@@@@@ SRC PANIC @@@@@@" "[line] ${LINENO}: ${BASH_COMMAND}" "[file] $_" "[code] $?";set +eo pipefail;trap - ERR;exit 113;while :;do read;done' ERR || exit 114
+trap 'printf "%s\n" "@@@@@@ SRC PANIC @@@@@@" "[line] ${LINENO}: ${BASH_COMMAND}" "[file] ${BASH_SOURCE}" "[code] $?";exit 113;while :;do read;done' ERR || exit 114
 EOM
 )
 # safety end
@@ -604,8 +625,14 @@ EOM
 #-------------------------------------------------------------------------------- HEADER
 printf "${BBLUE}%s${OFF}\n" "compiling [header] ***************"
 # BASH SHEBANG
-log::tab "#!/usr/bin/bash"
-echo "#!/usr/bin/bash" > "$TMP_HEADER"
+if [[ $BANG ]]; then
+	log::tab "$BANG"
+	echo "$BANG" > "$TMP_HEADER"
+else
+	BANG='#!/usr/bin/env -iS EDITOR="${EDITOR}" HOME="${HOME}" LANG="${LANG}" PATH="${PATH}" PWD="${PWD}" TERM="${TERM}" USER="${USER}" bash'
+	log::tab "$BANG"
+	echo "$BANG" > "$TMP_HEADER"
+fi
 
 # LICENSE
 if [[ $LICENSE ]]; then
@@ -869,7 +896,7 @@ chmod 700 "${OUTPUT}"
 if [[ $IGNORE = *ALL* || $IGNORE = *all* ]]; then
 	log::warn "skipping shellcheck"
 else
-	___ENDOF___ERROR___TRACE___
+	___ENDOF___TRACE___
 	log::info "starting shellcheck"
 	if [[ $QUIET = true ]]; then
 		if [[ $IGNORE ]]; then
@@ -884,7 +911,7 @@ else
 			shellcheck "${OUTPUT}" --shell bash || exit
 		fi
 	fi
-	___BEGIN___ERROR___TRACE___
+	___BEGIN___TRACE___
 fi
 
 # DELETE TMP_DIR
@@ -896,7 +923,7 @@ fi
 # FINAL
 log::ok "$OUTPUT"
 [[ $QUIET = true ]] && exec &>/dev/tty
-___ENDOF___ERROR___TRACE___
+___ENDOF___TRACE___
 }
 # EXECUTE
 hbc $@
