lib: -l | --library option to specify lib code directory

diff --git a/hbc b/hbc
--- a/hbc
+++ b/hbc
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
-#git <hbc/4e4a312>
-#nix <1656901932>
-#hbc <4e4a312>
+#git <hbc/f78c459>
+#nix <1656987103>
+#hbc <f78c459>
 #lib <stdlib/ask.sh/6cf3ad6>
 #lib <stdlib/log.sh/6cf3ad6>
 #lib <stdlib/trace.sh/6cf3ad6>
@@ -31,20 +31,64 @@ ask::no() {
 ask::sudo() {
 	sudo -v
 }
-log::dot() { printf "\033[1;37m[ \033[0m....\033[1;37m ]\033[0m %s\n" "$@" ;}
-log::prog() { printf "\033[1;37m[ \033[0m....\033[1;37m ]\033[0m %s\r" "$@" ;}
-log::tab() { printf "\033[0m         %s\n" "$@" ;}
-log::ok() { printf "\033[1;32m[  OK  ]\033[0m %s\n" "$@" ;}
-log::info() { printf "\033[1;37m[ INFO ]\033[0m %s\n" "$@" ;}
-log::warn() { printf "\033[1;33m[ WARN ]\033[0m %s\n" "$@" ;}
-log::fail() { printf "\033[1;31m[ FAIL ]\033[0m %s\n" "$@" ;}
-log::danger() { printf "\033[1;31m[DANGER]\033[0m %s\n" "$@" ;}
+log::ok() {
+	printf "\r%${COLUMNS}s" " "
+	printf "\r\033[1;32m[  OK  ]\033[0m %s\n" "$@"
+}
+log::info() {
+	printf "\r%${COLUMNS}s" " "
+	printf "\r\033[1;37m[ INFO ]\033[0m %s\n" "$@"
+}
+log::warn() {
+	printf "\r%${COLUMNS}s" " "
+	printf "\r\033[1;33m[ WARN ]\033[0m %s\n" "$@"
+}
+log::fail() {
+	printf "\r%${COLUMNS}s" " "
+	printf "\r\033[1;31m[ FAIL ]\033[0m %s\n" "$@"
+}
+log::danger() {
+	printf "\r%${COLUMNS}s" " "
+	printf "\r\033[1;31m[DANGER]\033[0m %s\n" "$@"
+}
+log::tab() {
+	printf "\r%${COLUMNS}s" " "
+	printf "\r\033[0m         %s\n" "$@"
+}
+log::prog() {
+	printf "\r%${COLUMNS}s" " "
+	printf "\r\033[1;37m[ \033[0m....\033[1;37m ]\033[0m %s " "$@"
+}
+log::debug() {
+	printf "\r%${COLUMNS}s" " "
+	if [[ -z $LOG_DEBUG_INIT_TIME ]]; then
+		declare -g LOG_DEBUG_INIT_TIME
+		LOG_DEBUG_INIT_TIME=${EPOCHREALTIME//./}
+		printf "\r\033[0;0m[debug 0.000000] %s\n" "$1"
+		return
+	fi
+	local LOG_DEBUG_ADJUSTED_TIME LOG_DEBUG_DOT_INSERTION
+	LOG_DEBUG_ADJUSTED_TIME=$((${EPOCHREALTIME//./}-LOG_DEBUG_INIT_TIME))
+	case ${#LOG_DEBUG_ADJUSTED_TIME} in
+		1) LOG_DEBUG_ADJUSTED_TIME=00000${LOG_DEBUG_ADJUSTED_TIME};;
+		2) LOG_DEBUG_ADJUSTED_TIME=0000${LOG_DEBUG_ADJUSTED_TIME};;
+		3) LOG_DEBUG_ADJUSTED_TIME=000${LOG_DEBUG_ADJUSTED_TIME};;
+		4) LOG_DEBUG_ADJUSTED_TIME=00${LOG_DEBUG_ADJUSTED_TIME};;
+		5) LOG_DEBUG_ADJUSTED_TIME=0${LOG_DEBUG_ADJUSTED_TIME};;
+	esac
+	LOG_DEBUG_DOT_INSERTION=$((${#LOG_DEBUG_ADJUSTED_TIME}-6))
+	if [[ $LOG_DEBUG_DOT_INSERTION -eq 0 ]]; then
+		printf "\r\033[0;0m[debug 0.${LOG_DEBUG_ADJUSTED_TIME}] %s\n" "$1"
+	else
+		printf "\r\033[0;0m[debug ${LOG_DEBUG_ADJUSTED_TIME:0:${LOG_DEBUG_DOT_INSERTION}}.${LOG_DEBUG_ADJUSTED_TIME:${LOG_DEBUG_DOT_INSERTION}}] %s\n" "$1"
+	fi
+}
 ___BEGIN___ERROR___TRACE___() {
 	POSIXLY_CORRECT= || exit 8
 	\unset -f trap set return exit printf unset local return read unalias mapfile kill builtin || exit 9
 	\unalias -a || exit 10
 	unset POSIXLY_CORRECT || exit 11
-	trap 'TRACE_CMD="$BASH_COMMAND" TRACE_FUNC="${BASH_LINENO[@]}" TRACE_CMD_NUM="$LINENO" TRACE_PIPE="${PIPESTATUS[@]}"; ___ENDOF___ERROR___TRACE___ || exit 100' ERR || exit 12
+	trap 'TRACE_CMD="$BASH_COMMAND" TRACE_FUNC=(${BASH_LINENO[@]}) TRACE_CMD_NUM="$LINENO" TRACE_PIPE=(${PIPESTATUS[@]}); ___ENDOF___ERROR___TRACE___ || exit 100' ERR || exit 12
 	unset -v TRACE_CMD TRACE_FUNC_NUM TRACE_CMD_NUM TRACE_PIPE || exit 13
 	set -E -e -o pipefail || exit 14
 	return 0
@@ -63,10 +107,6 @@ ___ENDOF___ERROR___TRACE___() {
 		set +E +eo pipefail || exit 24
 		trap - ERR || exit 25
 		return 0
-	fi
-	if [[ $TRACE_CMD =~ ^\(.*\)$ ]]; then
-		printf "\033[1;93m%s\n" "========    SHELLS KILLED    ========"
-		builtin kill $$ || exit 101
 	fi
 	printf "\033[1;91m%s\n" "========  BEGIN ERROR TRACE  ========"
 	printf "\033[1;95m%s\033[0m%s\n" "[bash] " "$BASH_VERSION"
@@ -115,10 +155,13 @@ ___ENDOF___ERROR___TRACE___() {
 		((TRACE_CMD_NUM++))
 	done
 	printf "\033[1;91m%s\033[0m\n" "========  ENDOF ERROR TRACE  ========"
+	[[ $TRACE_CMD =~ ^\(.*\)$ ]] && printf "\033[1;93m%s\033[0m\n" "========  SUB-SHELLS KILLED  ========"
 	unset -v TRACE_CMD TRACE_FUNC_NUM TRACE_CMD_NUM TRACE_PIPE || exit 26
 	set +E +eo pipefail || exit 27
 	trap - ERR || exit 28
-	exit 99
+	builtin kill -s SIGKILL $$ & exit 99
+	printf "\033[1;97m%s\033[0m\n" "= KILL FAIL, ENTERING INFINITE LOOP ="
+	while :; do read -s -r; done
 }
 readonly BLACK="\033[0;30m"
 readonly RED="\033[0;31m"
@@ -156,14 +199,14 @@ readonly OFF="\033[0m"
 declare -fr ask::yes
 declare -fr ask::no
 declare -fr ask::sudo
-declare -fr log::dot
-declare -fr log::prog
-declare -fr log::tab
 declare -fr log::ok
 declare -fr log::info
 declare -fr log::warn
 declare -fr log::fail
 declare -fr log::danger
+declare -fr log::tab
+declare -fr log::prog
+declare -fr log::debug
 declare -fr ___BEGIN___ERROR___TRACE___
 declare -fr ___ENDOF___ERROR___TRACE___
 trap - ERR || exit 117
@@ -181,7 +224,8 @@ if [[ $1 = "-h" || $1 = "--help" ]]; then
 cat << EOM
 USAGE: hbc [OPTION] [ARGUMENT]
     -d | --delete                       overwrite output file if it already exists
-    -i | --ignore  <shellcheck codes>   ignore shellcheck codes, formatting: -i SC2154,SC2155
+    -i | --ignore  <shellcheck codes>   ignore shellcheck codes, formatting: [-i SC2154,SC2155]
+    -l | --library <library directory>  specify where to look for lib code, default: [/usr/local/include]
     -m | --main    <main script name>   specify main script name, default: [main.sh]
     -h | --help                         print this help message and exit unsuccessfully
     -o | --output  <output name>        specify output filename, default: [\$FOLDER_NAME.sh]
@@ -206,6 +250,13 @@ case $1 in
 			exit 1
 		fi
 		local OPTION_IGNORE="$1"; shift;;
+	-l | --library)
+		shift
+		if [[ -z $1 ]]; then
+			log::fail "hbc: no arg after --library"
+			exit 1
+		fi
+		local LIB_DIRECTORY="$1"; shift;;
 	-m | --main)
 		shift
 		if [[ -z $1 ]]; then
@@ -244,11 +295,11 @@ fi
 # BOTH LIB/SRC NOT FOUND
 local EXISTS_LIB=true
 local SRC_FILES
-SRC_FILES=$(find src -name "*.sh" 2>/dev/null | cut -d '/' -f2 | sort)
+SRC_FILES=$(find src -regex ".*\.sh\|.*\.bash" 2>/dev/null | cut -d '/' -f2 | sort)
 if ! grep -m1 "^#include <.*>$" "$main" &>/dev/null; then
 	EXISTS_LIB=false
 	if [[ -z $SRC_FILES ]]; then
-		log::fail "both [lib/src] are missing" "no reason to use hbc" "exiting..."
+		log::fail "both [lib/src] are missing" "no reason to use hbc"
 		exit 1
 	fi
 fi
@@ -300,6 +351,7 @@ VERSION_HBC=$(grep -m1 "^#git <hbc/.*>$" "$0" | grep -o "\/.*>" | tr -d '/>')
 
 # LIB/SRC/MAIN
 local LIB_GIT
+[[ -z $LIB_DIRECTORY ]] && LIB_DIRECTORY="/usr/local/include"
 #local SRC_FILES # this gets defined in the beginning sanity check
 
 # MKTEMP
@@ -386,9 +438,9 @@ if [[ $EXISTS_LIB = true && $DIRECTORY_NAME != *lib ]]; then
 	printf "${BPURPLE}%s${OFF}\n" "compiling [lib] ******************"
 	local i
 	for i in $(grep "^#include <.*>$" "$main" | cut -d ' ' -f2 | tr -d '<>' | sort); do
-		if [[ $i = *.sh && -f /usr/local/include/$i ]]; then
-			sed "/^#\|[[:space:]]#/d" "/usr/local/include/$i" >> "$TMP_LIB"
-			LIB_GIT=$(grep "^#git <.*>$" "/usr/local/include/$i" | cut -d ' ' -f2)
+		if [[ $i = *.sh && -f "$LIB_DIRECTORY/$i" ]]; then
+			sed "/^#\|[[:space:]]#/d" "$LIB_DIRECTORY/$i" >> "$TMP_LIB"
+			LIB_GIT=$(grep "^#git <.*>$" "$LIB_DIRECTORY/$i" | cut -d ' ' -f2)
 			log::tab "$LIB_GIT"
 			echo "#lib $LIB_GIT" >> "$TMP_HEADER"
 		else
